### ISSUE TITLE
백로그

### ISSUE THREAD

**Issue by dbwp031** [dbwp031/OurWorldCup#33]
들어갈만한 기능들을 모두 나열해둔다. 해당 기능들은 구현 필수인 것, 있으면 좋은 것 모두 포함되어 있다.

### TODO
- [ ] 월드컵 디테일 페이지 만들기
- [ ] #44
- [ ] postman 사용 설정
- [ ] 월드컵 초대 코드 생성하기
- [ ] 초대 주소 카카오톡 보내기
- [ ] 월드컵 패스워드 encrpt해서 db 저장
- [x] #34
- [x] #36
- [x] #38
- [x] #40

**Comment by dbwp031** [comment]
- 초대 링크
  - 우선, 링크를 가지고 있는 사람 모두 멤버로 초대되도록 한다.
  - 이후에 제약을 거는 방법 고안
